files {
    'loading.html',
    'config.js',
    'script.js',
    'style.css',
    'music.ogg',
    'icon/crown.png',
    'icon/discord.png',
    'icon/facebook.png',
    'icon/music.png',
    'icon/person.png',
    'icon/tip.png',
    'icon/twitch.png',
    'icon/twitter.png',
    'icon/vulkanoa.png',
    'icon/youtube.png',
    'icon/website.png',
	'img/a.jpg',
    'img/b.jpg',
    'img/c.jpg',
    'img/d.jpg',
    'img/e.jpg',
    'img/f.jpg',
    'img/g.jpg',
    'img/i.jpg',
    'img/j.jpg',
    'img/k.jpg',
    'img/l.jpg',
    'img/n.jpg',
    'img/m.jpg',
    'img/o.jpg',
    'img/p.jpg',
}

loadscreen 'loading.html'