var tableauQuestion = [
    {   question : "Si estás circulando a más de 120km/h y entras en una zona residencial, debes:",
        propositionA : "ir más rápido",
        propositionB : "Mantener la velocidad",
        propositionC : "Disminuir la velocidad",
        propositionD : "Mantener la velocidad si no hay otros vehículos",
        reponse : "C"},

    {   question : "Si ves que hay un STOP, pero crees que no hay vehículos a los que ceder el paso ¿qué harías?:",
        propositionA : "Continuar mi camino y no parar.",
        propositionB : "Hacer como si el STOP fuera un ceda el paso, por lo tanto disminuir la velocidad.",
        propositionC : "Hacer el STOP aunque no haya coches, ya que es obligatorio.",
        propositionD : "Poner East Los FM y preguntarle a Don cheto.",
        reponse : "C"},

    {   question : "¿Cuál es la velocidad máxima en una zona residencial?",
        propositionA : "40",
        propositionB : "70",
        propositionC : "100",
        propositionD : "150",
        reponse : "A"},

  {   question : "Antes de cambiar de carril debes:",
        propositionA : "Ver cuanta gasolina te queda",
        propositionB : "Autos, moda y Rock & roll",
        propositionC : "ver que el que tengas detrás no te siga",
        propositionD : "Indicarlo con los intermitentes y ver que nadie vaya a adelantarte por ahí.",
        reponse : "D"},

  {   question : "Hoy el rey, no puede ser feliz porque no tiene:",
        propositionA : "Ni castillo ni bufón",
        propositionB : "ni amor ni dinero",
        propositionC : "Ni castillo ni amor",
        propositionD : "Mentira, el rey es feliz.",
        reponse : "C"},

  {   question : "¿Cuándo debes encender las luces de tráfico?",
        propositionA : "Cuando tenga coches cerca.",
        propositionB : "Cuando no vea.",
        propositionC : "Cuando esté cerca de vehículos de la policía o la EMS.",
        propositionD : "Cuando sea de noche.",
        reponse : "D"},

  {   question : "¿Qué debes hacer si atropellas a un peatón?",
        propositionA : "Me doy a la fuga",
        propositionB : "Meto el cadaver en el maletero",
        propositionC : "Le tiro unos billetes para los daños y me voy",
        propositionD : "Llamar a los médicos y a la policía.",
        reponse : "D"},

  {   question : "Si te estás meando y vas por la autopista",
        propositionA : "Te meas encima.",
        propositionB : "Meas por la ventana.",
        propositionC : "Paras en alguna área de servicio y ahí haces tus necesidades.",
        propositionD : "Carmen, se me perdió la cadenita, que tú me regalaste, Carmen.",
        reponse : "C"},

  {   question : "Si tienes un accidente de tráfico con otro conductor debes:",
        propositionA : "matarlo",
        propositionB : "reventarle el coche a tiros",
        propositionC : "matarlo y reventarle el coche a tiros",
        propositionD : "Antes de nada ver si está bien, luego llamar a la policía y al seguro.",
        reponse : "D"},

  {   question : "¿Qué pasa si un policía me pone las sirenas:",
        propositionA : "Significa que mi coche es bonito, es una manera de comunicarmelo",
        propositionB : "Significa que está escuchando East Los FM, la canción esa del pitido",
        propositionC : "Significa que tiene prisa",
        propositionD : "Si está detrás de mi, debo apartarme y parar el coche.",
        reponse : "D"},
]